denyAreaList:
  - world: "world"
    min:
      x: 0
      y: 0
      z: 0
    max:
      x: 100
      y: 100
      z: 100
  - world: "world"
    min:
      x: 50
      y: 50
      z: 50
    max:
      x: 150
      y: 150
      z: 150

ticketTeleport:
  # 冒険者ワールド
  - id: 101
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 鍛冶屋ワールド
  - id: 102
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # パン屋ワールド
  - id: 103
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 漁師ワールド
  - id: 104
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 木こりワールド
  - id: 105
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 剣士ワールド
  - id: 106
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 魔法使いワールド
  - id: 107
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 鍛冶屋ワールド
  - id: 108
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 裁縫師ワールド
  - id: 109
    world: "world_the_end"
    x: 0
    y: 0
    z: 0
  # 魔法研究員ワールド
  - id: 110
    world: "world_the_end"
    x: 0
    y: 0
    z: 0